#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#entreprises:
#    path: /entreprises
#    controller: App\Controller\DefaultController::affEntreprises
#formations:
#    path: /formations
#    controller: App\Controller\DefaultController::affFormations
#stages:
#    path: /stages
#    controller: App\Controller\DefaultController::affStages